import {
  clients,
  projects,
  tasks,
  payments,
  leads,
  employees,
  employeeTasks,
  followUpReminders,
  campaigns,
  users,
  approvals,
  activities,
  businessProjects,
  projectMilestones,
  projectPayments,
  hostingRecords,
  accountantDocuments,
  podcastSessions,
  aiSettings,
  clientKnowledge,
  gmailSettings,
} from './collections';
import type {
  Client,
  Project,
  Task,
  Payment,
  Lead,
  Employee,
  EmployeeTask,
  FollowUpReminder,
  Campaign,
  User,
  Approval,
  ActivityEntry,
  BusinessProject,
  ProjectMilestone,
  ProjectPayment,
  HostingRecord,
  AccountantDocument,
  PodcastSession,
  AISettings,
  ClientKnowledge,
} from './schema';

const now = new Date().toISOString();
const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
const nextWeek = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
const nextMonth = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

export function seedIfEmpty(): void {
  if (
    clients.count() === 0 &&
    projects.count() === 0 &&
    tasks.count() === 0 &&
    payments.count() === 0 &&
    leads.count() === 0 &&
    employees.count() === 0 &&
    campaigns.count() === 0 &&
    users.count() === 0 &&
    approvals.count() === 0 &&
    activities.count() === 0
  ) {
    seed();
  }
}

export function ensureSeeded(): void {
  seedIfEmpty();
}

function seed(): void {
  // Create employees first (needed for task assignment)
  const employee1 = employees.create({
    name: 'טל זטלמן',
    roleId: 'role_admin',
    role: 'admin',
    email: 'tal@s-pixel.co.il',
    phone: '054-1234567',
    avatarUrl: '',
    salary: 15000,
    status: 'online',
    skills: ['ניהול', 'אסטרטגיה', 'וידאו', 'עיצוב'],
    tasksCount: 5,
    workload: 75,
    joinDate: '2021-01-01',
    notes: 'מנכ"ל ומנהל סטודיו',
    createdAt: now,
    updatedAt: now,
  });

  const employee2 = employees.create({
    name: 'מאיה זטלמן',
    roleId: 'role_manager',
    role: 'manager',
    email: 'maya@s-pixel.co.il',
    phone: '054-9876543',
    avatarUrl: '',
    salary: 13000,
    status: 'online',
    skills: ['ניהול לקוחות', 'שיווק', 'תוכן', 'רשתות חברתיות'],
    tasksCount: 8,
    workload: 85,
    joinDate: '2021-01-01',
    notes: 'מנהלת לקוחות ותוכן',
    createdAt: now,
    updatedAt: now,
  });

  const employee3 = employees.create({
    name: 'נועם בוברין',
    roleId: 'role_employee',
    role: 'employee',
    email: 'noam@s-pixel.co.il',
    phone: '054-5555555',
    avatarUrl: '',
    salary: 11000,
    status: 'online',
    skills: ['עריכת וידאו', 'אנימציה', 'עיצוב גרפי'],
    tasksCount: 12,
    workload: 95,
    joinDate: '2023-06-10',
    notes: 'עורך וידאו ומעצב',
    createdAt: now,
    updatedAt: now,
  });

  const employee4 = employees.create({
    name: 'מיכאלה',
    roleId: 'role_employee',
    role: 'employee',
    email: 'michaela@s-pixel.co.il',
    phone: '054-7777777',
    avatarUrl: '',
    salary: 10000,
    status: 'online',
    skills: ['תוכן', 'קופירייטינג', 'רשתות חברתיות'],
    tasksCount: 6,
    workload: 70,
    joinDate: '2024-02-15',
    notes: 'כותבת תוכן וניהול רשתות',
    createdAt: now,
    updatedAt: now,
  });

  // Create clients
  const client1 = clients.create({
    name: 'סטודיו פיקסל',
    company: 'Pixel Studio Ltd',
    contactPerson: 'יחיאל רון',
    email: 'yechiel@pixelstudio.co.il',
    phone: '03-1234567',
    logoUrl: '',
    color: '#FF6B6B',
    clientType: 'marketing',
    businessField: 'פיתוח תוכן',
    marketingGoals: 'הגדלת החשיפה הדיגיטלית והעלאת המעורבות בסוציאל מדיה',
    keyMarketingMessages: 'תוכן ווידיאו חדשני וקריאטיבי, שירות אישי למשכירים',
    assignedManagerId: employee1.id,
    websiteUrl: 'https://pixelstudio.co.il',
    facebookPageUrl: 'https://facebook.com/pixelstudio',
    instagramProfileUrl: 'https://instagram.com/pixel_studio',
    tiktokProfileUrl: 'https://tiktok.com/@pixelstudio2024',
    retainerAmount: 5000,
    retainerDay: 1,
    paymentStatus: 'current',
    nextPaymentDate: nextMonth,
    status: 'active',
    notes: 'חברה מובילה בתעשיית הווידיאו',
    convertedFromLead: null,
    createdAt: now,
    updatedAt: now,
    portalEnabled: true,
    portalUserId: null,
    lastPortalLoginAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    facebookPageId: '123456789',
    facebookPageName: 'Pixel Studio',
    instagramAccountId: 'pixel_studio_official',
    instagramUsername: '@pixel_studio',
    tiktokAccountId: 'pixelstudio2024',
    tiktokUsername: '@pixelstudio2024',
    monthlyGanttStatus: 'approved',
    annualGanttStatus: 'approved',
  });

  const client2 = clients.create({
    name: 'ברנדיפיי',
    company: 'Brandify Media',
    contactPerson: 'נגה לב',
    email: 'noga@brandify.co.il',
    phone: '03-9876543',
    logoUrl: '',
    color: '#4ECDC4',
    clientType: 'branding',
    businessField: 'שיווק',
    marketingGoals: 'בניית זהות חזקה ועקביות על כל הערוצים, הגדלת הכרה למותג',
    keyMarketingMessages: 'שיווק מעביד חדשני וניתנת התאמה, מומחים בבניית ברנדים',
    assignedManagerId: employee4.id,
    websiteUrl: 'https://brandify.co.il',
    facebookPageUrl: 'https://facebook.com/brandify',
    instagramProfileUrl: 'https://instagram.com/brandify_media',
    tiktokProfileUrl: '',
    retainerAmount: 3500,
    retainerDay: 15,
    paymentStatus: 'overdue',
    nextPaymentDate: tomorrow,
    status: 'active',
    notes: 'סוכנות שיווק דיגיטלית',
    convertedFromLead: null,
    createdAt: now,
    updatedAt: now,
    portalEnabled: true,
    portalUserId: null,
    lastPortalLoginAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    facebookPageId: 'brandify_official',
    facebookPageName: 'Brandify Media',
    instagramAccountId: '987654321',
    instagramUsername: '@brandify_official',
    tiktokAccountId: '',
    tiktokUsername: '',
    monthlyGanttStatus: 'draft',
    annualGanttStatus: 'sent_to_client',
  });

  const client3 = clients.create({
    name: 'טקבולט',
    company: 'TechBolt Inc',
    contactPerson: 'שלום בן אברהם',
    email: 'shalom@techbolt.io',
    phone: '03-5555555',
    logoUrl: '',
    color: '#95E1D3',
    clientType: 'websites',
    businessField: 'טכנולוגיה',
    marketingGoals: 'הדגמת פתרונות טכנולוגיים מקדימים, קבלת עופד חדשות',
    keyMarketingMessages: 'אינטגרציה עםענן, קנה מידה, אבטחה של דרגה אנטרפרייז',
    assignedManagerId: employee2.id,
    websiteUrl: 'https://studioflex.com',
    facebookPageUrl: 'https://facebook.com/studioflex',
    instagramProfileUrl: 'https://instagram.com/studio.flex',
    tiktokProfileUrl: 'https://tiktok.com/@techbolt_official',
    retainerAmount: 6000,
    retainerDay: 10,
    paymentStatus: 'current',
    nextPaymentDate: nextWeek,
    status: 'active',
    notes: 'חברת היי-טק בתחום הקלאוד',
    convertedFromLead: null,
    createdAt: now,
    updatedAt: now,
    portalEnabled: true,
    portalUserId: null,
    lastPortalLoginAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    facebookPageId: '',
    facebookPageName: '',
    instagramAccountId: '',
    instagramUsername: '',
    tiktokAccountId: 'techbolt_official',
    tiktokUsername: '@techbolt_official',
    monthlyGanttStatus: 'approved',
    annualGanttStatus: 'client_approved',
  });

  const client4 = clients.create({
    name: 'גרין ליף',
    company: 'GreenLeaf Organic',
    contactPerson: 'רחל ירוק',
    email: 'rachel@greenleaf.co.il',
    phone: '04-2222222',
    logoUrl: '',
    color: '#52B788',
    clientType: 'marketing',
    businessField: 'קמעונאות',
    marketingGoals: 'שיווק מוצרים אורגניים לצרכנים מודעים סביבתית',
    keyMarketingMessages: 'מוצרים טבעיים נקיים, ערכים סביבתיים, בריאות חיובית',
    assignedManagerId: employee4.id,
    websiteUrl: 'https://greenleaf.co.il',
    facebookPageUrl: 'https://facebook.com/greenleaforganic',
    instagramProfileUrl: 'https://instagram.com/greenleaf_organic',
    tiktokProfileUrl: '',
    retainerAmount: 2000,
    retainerDay: 20,
    paymentStatus: 'pending',
    nextPaymentDate: nextMonth,
    status: 'prospect',
    notes: 'משלחת אורגנית וירוקה',
    convertedFromLead: null,
    createdAt: now,
    updatedAt: now,
    portalEnabled: false,
    portalUserId: null,
    lastPortalLoginAt: null,
    facebookPageId: '',
    facebookPageName: '',
    instagramAccountId: '',
    instagramUsername: '',
    tiktokAccountId: '',
    tiktokUsername: '',
    monthlyGanttStatus: 'none',
    annualGanttStatus: 'none',
  });

  const client5 = clients.create({
    name: 'נקסט לevel',
    company: 'NextLevel Gaming',
    contactPerson: 'דוד משחקי',
    email: 'david@nextlevel.io',
    phone: '03-4444444',
    logoUrl: '',
    color: '#9D4EDD',
    clientType: 'branding',
    businessField: 'בידור',
    marketingGoals: 'שיווק משחקים חדשים, בניית קהילה של משחקים',
    keyMarketingMessages: 'משחקים חדשים וחדשים, עמק תוכן מעניין, משחקנים מ"זקיקים"',
    assignedManagerId: employee1.id,
    websiteUrl: 'https://nextlevel.io',
    facebookPageUrl: 'https://facebook.com/nextlevelgaming',
    instagramProfileUrl: 'https://instagram.com/nextlevel_gaming',
    tiktokProfileUrl: '',
    retainerAmount: 4000,
    retainerDay: 5,
    paymentStatus: 'none',
    nextPaymentDate: null,
    status: 'inactive',
    notes: 'סטודיו משחקים',
    convertedFromLead: null,
    createdAt: now,
    updatedAt: now,
    portalEnabled: false,
    portalUserId: null,
    lastPortalLoginAt: null,
    facebookPageId: '',
    facebookPageName: '',
    instagramAccountId: '',
    instagramUsername: '',
    tiktokAccountId: '',
    tiktokUsername: '',
    monthlyGanttStatus: 'draft',
    annualGanttStatus: 'none',
  });

  const client6 = clients.create({
    name: 'ארט סpeice',
    company: 'ArtSpace Gallery',
    contactPerson: 'ענת כהן',
    email: 'anat@artspace.co.il',
    phone: '02-6666666',
    logoUrl: '',
    color: '#F72585',
    clientType: 'hosting',
    businessField: 'אמנות ותרבות',
    marketingGoals: 'הנחת יצירות אמנות חדשות, יצירת ביקורות אמנות, הגדלת קהל',
    keyMarketingMessages: 'בטיחות מהחנויות יוקרתיות, אומנותיות מעולה, אירועים בעלי משקעות',
    assignedManagerId: null,
    websiteUrl: 'https://artspace.co.il',
    facebookPageUrl: 'https://facebook.com/artspacegallery',
    instagramProfileUrl: 'https://instagram.com/artspace.gallery',
    tiktokProfileUrl: 'https://tiktok.com/@artspace_gallery',
    retainerAmount: 2500,
    retainerDay: 25,
    paymentStatus: 'current',
    nextPaymentDate: nextMonth,
    status: 'active',
    notes: 'גלריה לאמנות עדכנית',
    convertedFromLead: null,
    createdAt: now,
    updatedAt: now,
    portalEnabled: true,
    portalUserId: null,
    lastPortalLoginAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    facebookPageId: '555666777',
    facebookPageName: 'ArtSpace Gallery',
    instagramAccountId: 'artspace_gallery',
    instagramUsername: '@artspace_gallery',
    tiktokAccountId: '',
    tiktokUsername: '',
    monthlyGanttStatus: 'approved',
    annualGanttStatus: 'draft',
  });

  // Create projects
  const project1 = projects.create({
    name: 'וידיאו פתיחה לדוקומנטר',
    clientId: client1.id,
    clientName: client1.name,
    status: 'complete',
    format: '16:9',
    preset: 'קולנוע',
    durationSec: 45,
    segments: 5,
    sourceVideoKey: 'video_001.mp4',
    renderOutputKey: 'render_001_final.mp4',
    thumbnailKey: 'thumb_001.jpg',
    wizardState: null,
    renderPayload: null,
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project2 = projects.create({
    name: 'סרטון פרסומי לתוכן ברנדיפיי',
    clientId: client2.id,
    clientName: client2.name,
    status: 'rendering',
    format: '9:16',
    preset: 'סוציאלי מדיה',
    durationSec: 30,
    segments: 3,
    sourceVideoKey: 'video_002.mp4',
    renderOutputKey: null,
    thumbnailKey: null,
    wizardState: { step: 2, quality: 'high' },
    renderPayload: { codec: 'h264', bitrate: '5mbps' },
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project3 = projects.create({
    name: 'הדמיה טכנולוגית - טקבולט',
    clientId: client3.id,
    clientName: client3.name,
    status: 'analysing',
    format: '16:9',
    preset: 'טכנולוגיה',
    durationSec: 60,
    segments: 8,
    sourceVideoKey: 'video_003.mp4',
    renderOutputKey: null,
    thumbnailKey: null,
    wizardState: null,
    renderPayload: null,
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project4 = projects.create({
    name: 'קמפיין סוציאלי - גרין ליף',
    clientId: client4.id,
    clientName: client4.name,
    status: 'approved',
    format: '1:1',
    preset: 'אינסטגרם',
    durationSec: 20,
    segments: 2,
    sourceVideoKey: 'video_004.mp4',
    renderOutputKey: null,
    thumbnailKey: 'thumb_004.jpg',
    wizardState: null,
    renderPayload: null,
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project5 = projects.create({
    name: 'טריילר משחק - נקסט לevel',
    clientId: client5.id,
    clientName: client5.name,
    status: 'draft',
    format: '16:9',
    preset: 'קולנוע',
    durationSec: 90,
    segments: 12,
    sourceVideoKey: null,
    renderOutputKey: null,
    thumbnailKey: null,
    wizardState: { step: 0 },
    renderPayload: null,
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project6 = projects.create({
    name: 'קולקשן סוכנות אומנות',
    clientId: client6.id,
    clientName: client6.name,
    status: 'failed',
    format: '4:5',
    preset: 'אמנות',
    durationSec: 25,
    segments: 4,
    sourceVideoKey: 'video_006.mp4',
    renderOutputKey: null,
    thumbnailKey: null,
    wizardState: null,
    renderPayload: null,
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project7 = projects.create({
    name: 'סדרת טיפים - סטודיו פיקסל',
    clientId: client1.id,
    clientName: client1.name,
    status: 'rendering',
    format: '9:16',
    preset: 'TikTok',
    durationSec: 15,
    segments: 1,
    sourceVideoKey: 'video_007.mp4',
    renderOutputKey: null,
    thumbnailKey: null,
    wizardState: null,
    renderPayload: { codec: 'vp9' },
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  const project8 = projects.create({
    name: 'וידיאו תצוגה מוקד - ברנדיפיי',
    clientId: client2.id,
    clientName: client2.name,
    status: 'draft',
    format: '16:9',
    preset: 'אתר',
    durationSec: 120,
    segments: 6,
    sourceVideoKey: null,
    renderOutputKey: null,
    thumbnailKey: null,
    wizardState: null,
    renderPayload: null,
    sentToClientAt: null,
    sentToClientEmail: null,
    createdAt: now,
    updatedAt: now,
  });

  // Create tasks
  const task1 = tasks.create({
    title: 'בדוק עיצוב וידיאו חדש',
    description: 'ביקורת נתונים על עיצוב הווידיאו החדש מ-סטודיו פיקסל',
    status: 'new',
    priority: 'high',
    clientId: client1.id,
    clientName: client1.name,
    assigneeIds: [employee1.id],
    dueDate: tomorrow,
    tags: ['חשוב', 'ביקורת'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task2 = tasks.create({
    title: 'ערוך וידיאו פרסום',
    description: 'עריכה של וידיאו הפרסום להשקת ברנדיפיי',
    status: 'in_progress',
    priority: 'high',
    clientId: client2.id,
    clientName: client2.name,
    assigneeIds: [employee2.id],
    dueDate: nextWeek,
    tags: ['עריכה', 'פרסום'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task3 = tasks.create({
    title: 'הוסף אפקטים מיוחדים',
    description: 'הוסף אפקטים מיוחדים לסרטון ההדמיה',
    status: 'in_progress',
    priority: 'medium',
    clientId: client3.id,
    clientName: client3.name,
    assigneeIds: [employee3.id, employee4.id],
    dueDate: nextWeek,
    tags: ['אפקטים'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task4 = tasks.create({
    title: 'איתור צבע שמור',
    description: 'בחר את צבע ה-brand הנכון לקמפיין',
    status: 'under_review',
    priority: 'medium',
    clientId: client4.id,
    clientName: client4.name,
    assigneeIds: [employee1.id],
    dueDate: nextMonth,
    tags: ['עיצוב'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task5 = tasks.create({
    title: 'כתוב תסריט טריילר',
    description: 'כתוב תסריט מקצועי לטריילר המשחק החדש',
    status: 'completed',
    priority: 'high',
    clientId: client5.id,
    clientName: client5.name,
    assigneeIds: [employee4.id],
    dueDate: null,
    tags: ['תסריט'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task6 = tasks.create({
    title: 'תאם דרישות נכסים',
    description: 'תאם נכסים עם דרישות אמנות חדשות',
    status: 'new',
    priority: 'low',
    clientId: client6.id,
    clientName: client6.name,
    assigneeIds: [],
    dueDate: null,
    tags: ['אמנות'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task7 = tasks.create({
    title: 'בדוק טיפ וידיאו חדש',
    description: 'בדוק את סדרת הטיפים החדשה לפני הפרסום',
    status: 'new',
    priority: 'medium',
    clientId: client1.id,
    clientName: client1.name,
    assigneeIds: [employee2.id],
    dueDate: nextWeek,
    tags: ['בדיקה', 'פרסום'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  const task8 = tasks.create({
    title: 'הכן הצעה לתצוגה מוקד',
    description: 'הכן הצעה עבור וידיאו התצוגה המוקד החדש',
    status: 'new',
    priority: 'medium',
    clientId: client2.id,
    clientName: client2.name,
    assigneeIds: [employee4.id],
    dueDate: nextMonth,
    tags: ['הצעה'],
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  // Create payments
  const payment1 = payments.create({
    clientId: client1.id,
    clientName: client1.name,
    invoiceNo: 'INV-001',
    type: 'invoice',
    amount: 8500,
    status: 'paid',
    dueDate: now,
    paidAt: now,
    description: 'וידיאו פתיחה לדוקומנטר',
    createdAt: now,
    updatedAt: now,
  });

  const payment2 = payments.create({
    clientId: client2.id,
    clientName: client2.name,
    invoiceNo: 'INV-002',
    type: 'invoice',
    amount: 5000,
    status: 'pending',
    dueDate: tomorrow,
    paidAt: null,
    description: 'סרטון פרסומי',
    createdAt: now,
    updatedAt: now,
  });

  const payment3 = payments.create({
    clientId: client3.id,
    clientName: client3.name,
    invoiceNo: 'INV-003',
    type: 'retainer',
    amount: 6000,
    status: 'msg_sent',
    dueDate: nextWeek,
    paidAt: null,
    description: 'תשלום תאריך בספטמבר',
    createdAt: now,
    updatedAt: now,
  });

  const payment4 = payments.create({
    clientId: client4.id,
    clientName: client4.name,
    invoiceNo: 'INV-004',
    type: 'milestone',
    amount: 3000,
    status: 'overdue',
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    paidAt: null,
    description: 'עמלה על סיום שלב 1',
    createdAt: now,
    updatedAt: now,
  });

  const payment5 = payments.create({
    clientId: client6.id,
    clientName: client6.name,
    invoiceNo: 'INV-005',
    type: 'invoice',
    amount: 4500,
    status: 'write_off',
    dueDate: now,
    paidAt: null,
    description: 'הוצאות פרויקט שנויים',
    createdAt: now,
    updatedAt: now,
  });

  // Create leads
  const lead1 = leads.create({
    fullName: 'אברהם גולדברג',
    name: 'אברהם גולדברג',
    company: 'קולנוע בעולם',
    email: 'abraham@cinema.co.il',
    phone: '03-1112222',
    source: 'אתר אינטרנט',
    interestType: 'marketing',
    proposalSent: false,
    proposalAmount: 15000,
    status: 'new',
    followupDone: false,
    value: 15000,
    notes: 'מעוניין בניהול רשתות חברתיות לרשת בתי קולנוע',
    assigneeId: employee1.id,
    followUpAt: nextWeek,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: now,
    updatedAt: now,
  });

  const lead2 = leads.create({
    fullName: 'רית לוין',
    name: 'רית לוין',
    company: 'מוקד מכירות B2B',
    email: 'rit@b2bsales.co.il',
    phone: '09-5551234',
    source: 'LinkedIn',
    interestType: 'marketing',
    proposalSent: true,
    proposalAmount: 4500,
    status: 'proposal_sent',
    followupDone: false,
    value: 4500,
    notes: 'מעוניינת בשמירה שנתית על רשתות חברתיות',
    assigneeId: employee2.id,
    followUpAt: nextMonth,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: now,
    updatedAt: now,
  });

  const lead3 = leads.create({
    fullName: 'נתן כרמי',
    name: 'נתן כרמי',
    company: 'סטודיו דיזיטל חדש',
    email: 'natan@digitalstudio.io',
    phone: '03-3333333',
    source: 'המלצה',
    interestType: 'branding',
    proposalSent: true,
    proposalAmount: 12000,
    status: 'negotiation',
    followupDone: true,
    value: 12000,
    notes: 'מצפים למיתוג מלא כולל לוגו, שפה עיצובית ואתר',
    assigneeId: employee1.id,
    followUpAt: nextWeek,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: now,
    updatedAt: now,
  });

  const lead4 = leads.create({
    fullName: 'יוליה פטרוב',
    name: 'יוליה פטרוב',
    company: 'מודל סוציאלית',
    email: 'yulia@socialmodel.co.il',
    phone: '054-9998888',
    source: 'אינסטגרם',
    interestType: 'podcast',
    proposalSent: false,
    proposalAmount: 849,
    status: 'contacted',
    followupDone: false,
    value: 849,
    notes: 'מעוניינת בהקלטת פודקאסט - חבילת 3 סרטונים',
    assigneeId: null,
    followUpAt: nextMonth,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: now,
    updatedAt: now,
  });

  const lead5 = leads.create({
    fullName: 'דן שמי',
    name: 'דן שמי',
    company: 'שידורים ממשיכים',
    email: 'dan@streaming.io',
    phone: '02-4444444',
    source: 'פייסבוק',
    interestType: 'website',
    proposalSent: true,
    proposalAmount: 8500,
    status: 'negotiation',
    followupDone: true,
    value: 8500,
    notes: 'בניית אתר תדמית + דף נחיתה - בשיחות סגורות',
    assigneeId: employee2.id,
    followUpAt: tomorrow,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: now,
    updatedAt: now,
  });

  const lead6 = leads.create({
    fullName: 'שירה אבני',
    name: 'שירה אבני',
    company: 'מאפייה ביתית',
    email: 'shira@homebakery.co.il',
    phone: '054-2223333',
    source: 'המלצה',
    interestType: 'marketing',
    proposalSent: false,
    proposalAmount: 0,
    status: 'new',
    followupDone: false,
    value: 0,
    notes: 'השאירה פרטים דרך הטופס באתר - מעוניינת בניהול רשתות',
    assigneeId: null,
    followUpAt: null,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: now,
    updatedAt: now,
  });

  const lead7 = leads.create({
    fullName: 'עמית רוזנברג',
    name: 'עמית רוזנברג',
    company: 'FitLife Studio',
    email: 'amit@fitlife.co.il',
    phone: '050-8887777',
    source: 'Google Ads',
    interestType: 'other',
    proposalSent: true,
    proposalAmount: 3200,
    status: 'won',
    followupDone: true,
    value: 3200,
    notes: 'סגרנו חבילת תוכן חודשית - ממיר ללקוח',
    assigneeId: employee1.id,
    followUpAt: null,
    convertedAt: now,
    convertedClientId: null,
    convertedEntityType: 'client',
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: now,
  });

  const lead8 = leads.create({
    fullName: 'מוריה כץ',
    name: 'מוריה כץ',
    company: 'בוטיק אופנה',
    email: 'moriah@boutique.co.il',
    phone: '054-1119999',
    source: 'אירוע',
    interestType: 'branding',
    proposalSent: false,
    proposalAmount: 0,
    status: 'not_relevant',
    followupDone: true,
    value: 0,
    notes: 'לא רלוונטית כרגע - תקציב נמוך מדי',
    assigneeId: employee2.id,
    followUpAt: null,
    convertedAt: null,
    convertedClientId: null,
    convertedEntityType: null,
    convertedEntityId: null,
    campaignId: null,
    campaignName: '',
    adAccountId: '',
    adSetName: '',
    adName: '',
    clientId: null,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: now,
  });

  // Create employee tasks
  employeeTasks.create({
    title: 'עיצוב פוסט חדש לסטודיו פיקסל',
    description: 'עיצוב 3 פוסטים לפייסבוק ואינסטגרם',
    assignedEmployeeId: employee3.id,
    clientId: client1.id,
    clientName: client1.name,
    projectId: null,
    ganttItemId: null,
    dueDate: tomorrow,
    status: 'in_progress',
    priority: 'high',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'כתיבת תוכן חודשי למגנט לידים',
    description: 'קופירייטינג ל-12 פוסטים',
    assignedEmployeeId: employee4.id,
    clientId: client2.id,
    clientName: client2.name,
    projectId: null,
    ganttItemId: null,
    dueDate: nextWeek,
    status: 'new',
    priority: 'medium',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'עריכת סרטון לבית הקפה',
    description: 'עריכת סרטון קצר של 30 שניות לאינסטגרם',
    assignedEmployeeId: employee3.id,
    clientId: client3.id,
    clientName: client3.name,
    projectId: null,
    ganttItemId: null,
    dueDate: tomorrow,
    status: 'under_review',
    priority: 'urgent',
    files: ['video_draft_cafe.mp4'],
    notes: 'העלתי טיוטה ראשונה - ממתין לאישור',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'אישור גאנט חודשי - TechStart',
    description: 'בדיקה ואישור לוח תוכן אפריל',
    assignedEmployeeId: employee2.id,
    clientId: client4.id,
    clientName: client4.name,
    projectId: null,
    ganttItemId: null,
    dueDate: now,
    status: 'new',
    priority: 'high',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'פולואפ על הצעת מחיר - נתן כרמי',
    description: 'התקשר לנתן כרמי לגבי הצעת המיתוג',
    assignedEmployeeId: employee1.id,
    clientId: null,
    clientName: '',
    projectId: null,
    ganttItemId: null,
    dueDate: tomorrow,
    status: 'new',
    priority: 'high',
    files: [],
    notes: 'ליד מעוניין במיתוג - הצעה נשלחה, צריך לסגור',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'עיצוב לוגו חדש - פרויקט מיתוג',
    description: '3 כיוונים עיצוביים ללוגו',
    assignedEmployeeId: employee3.id,
    clientId: client5.id,
    clientName: client5.name,
    projectId: null,
    ganttItemId: null,
    dueDate: nextWeek,
    status: 'returned',
    priority: 'medium',
    files: ['logo_v1.pdf', 'logo_v2.pdf'],
    notes: 'הלקוח ביקש שינויים - צבעים חמים יותר',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'הכנת דוח ביצועים חודשי',
    description: 'סיכום ביצועי רשתות חברתיות - כל הלקוחות',
    assignedEmployeeId: employee2.id,
    clientId: null,
    clientName: '',
    projectId: null,
    ganttItemId: null,
    dueDate: nextWeek,
    status: 'in_progress',
    priority: 'medium',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  employeeTasks.create({
    title: 'משימה שפג תוקפה - דחוף!',
    description: 'פוסט שהיה צריך לצאת אתמול',
    assignedEmployeeId: employee3.id,
    clientId: client1.id,
    clientName: client1.name,
    projectId: null,
    ganttItemId: null,
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'in_progress',
    priority: 'urgent',
    files: [],
    notes: 'באיחור! צריך לסיים היום',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: now,
  });

  // Create campaigns
  const campaign1 = campaigns.create({
    campaignName: 'קמפיין סתיו 2024',
    clientId: client1.id,
    clientName: client1.name,
    campaignType: 'paid_social',
    objective: 'הגדלת מודעות למוצרים חדשים בקרב צעירים ומבוגרים',
    platform: 'multi_platform',
    status: 'active',
    budget: 50000,
    caption: 'גלו את הדור החדש של המוצרים שלנו. מאמילים להשקה דיגיטלית מתקדמת.',
    mediaType: 'video',
    linkedVideoProjectId: project1.id,
    linkedClientFileId: null,
    externalMediaUrl: '',
    notes: 'קמפיין עיקרי להשקת מוצרים חדשים. התמקד ברשתות חברתיות.',
    startDate: now,
    endDate: nextMonth,
    adAccountId: '',
    leadFormIds: [],
    createdAt: now,
    updatedAt: now,
  });

  const campaign2 = campaigns.create({
    campaignName: 'יום הלידה של ברנדיפיי - חגיגה דיגיטלית',
    clientId: client2.id,
    clientName: client2.name,
    campaignType: 'organic_social',
    objective: 'חיזוק הנוכחות הארגונית בחגיגת יום הלידה השנתי',
    platform: 'facebook',
    status: 'draft',
    budget: 25000,
    caption: 'אנחנו חוגגים 10 שנים של חדשנות ודעות מעמיקה! הצטרפו להחגיגה הדיגיטלית שלנו.',
    mediaType: 'image',
    linkedVideoProjectId: null,
    linkedClientFileId: null,
    externalMediaUrl: '',
    notes: 'קמפיין בוקדן בשנה הבאה. מתוכננת להשקה בחודש שלוש.',
    startDate: null,
    endDate: null,
    adAccountId: '',
    leadFormIds: [],
    createdAt: now,
    updatedAt: now,
  });

  const campaign3 = campaigns.create({
    campaignName: 'סדרת הובלת ליד חדשה',
    clientId: client3.id,
    clientName: client3.name,
    campaignType: 'lead_gen',
    objective: 'ניצול הזדמנויות חדשות לצמיחה עסקית דרך דיגיטל',
    platform: 'instagram',
    status: 'waiting_approval',
    budget: 30000,
    caption: 'אנחנו מחפשים שותפים חדשים לטיפול מעמיק. אם אתה משוויא בתחום, בואו נדבר.',
    mediaType: 'video',
    linkedVideoProjectId: project3.id,
    linkedClientFileId: null,
    externalMediaUrl: '',
    notes: 'הצעה מחכה לאישור מהלקוח. משובצת להפעלה לאחר אישור.',
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: nextMonth,
    adAccountId: '',
    leadFormIds: [],
    createdAt: now,
    updatedAt: now,
  });

  const campaign4 = campaigns.create({
    campaignName: 'מודעות למוצר פלגשי חדש',
    clientId: client1.id,
    clientName: client1.name,
    campaignType: 'awareness',
    objective: 'בנייה של מודעות מקדימה לפני השקה רשמית של מוצר',
    platform: 'tiktok',
    status: 'scheduled',
    budget: 18000,
    caption: 'הישומר על עדכונים. משהו גדול מתקרב לעולם!',
    mediaType: 'video',
    linkedVideoProjectId: null,
    linkedClientFileId: null,
    externalMediaUrl: 'https://example.com/teaser-video.mp4',
    notes: 'קמפיין teaser מתוכנן להתחיל בשבוע הבא.',
    startDate: nextWeek,
    endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    adAccountId: '',
    leadFormIds: [],
    createdAt: now,
    updatedAt: now,
  });

  const campaign5 = campaigns.create({
    campaignName: 'רימרקטינג קוקיס לא מומר',
    clientId: client2.id,
    clientName: client2.name,
    campaignType: 'remarketing',
    objective: 'חזרה ממירה של מבקרים שלא השלימו קניה',
    platform: 'multi_platform',
    status: 'completed',
    budget: 12000,
    caption: 'שכחת את הפריטים בעגלה שלך? חזור אלינו בהנחה מיוחדת של 15%!',
    mediaType: 'image',
    linkedVideoProjectId: null,
    linkedClientFileId: null,
    externalMediaUrl: '',
    notes: 'קמפיין רימרקטינג שהסתיים בהצלחה עם קצב המרה של 8%.',
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    adAccountId: '',
    leadFormIds: [],
    createdAt: now,
    updatedAt: now,
  });

  // Create users
  const user1 = users.create({
    name: 'טל זטלמן',
    email: 'tal@pixelframe.ai',
    role: 'admin',
    avatar: null,
    status: 'active',
    createdAt: now,
    lastSeen: now,
  });

  const user2 = users.create({
    name: 'דנה כהן',
    email: 'dana@pixelframe.ai',
    role: 'editor',
    avatar: null,
    status: 'active',
    createdAt: now,
    lastSeen: now,
  });

  const user3 = users.create({
    name: 'מיכל ברגר',
    email: 'michal@pixelframe.ai',
    role: 'manager',
    avatar: null,
    status: 'active',
    createdAt: now,
    lastSeen: now,
  });

  const user4 = users.create({
    name: 'אור שטיין',
    email: 'or@pixelframe.ai',
    role: 'viewer',
    avatar: null,
    status: 'active',
    createdAt: now,
    lastSeen: now,
  });

  // Create approvals
  const approval1 = approvals.create({
    type: 'video',
    title: 'וידיאו פתיחה - סטודיו פיקסל',
    clientName: client1.name,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
  });

  const approval2 = approvals.create({
    type: 'post',
    title: 'פוסט סוציאלי - ברנדיפיי',
    clientName: client2.name,
    status: 'pending_approval',
    createdAt: now,
    updatedAt: now,
  });

  const approval3 = approvals.create({
    type: 'design',
    title: 'עיצוב גרפיקי - טקבולט',
    clientName: client3.name,
    status: 'needs_changes',
    createdAt: now,
    updatedAt: now,
  });

  const approval4 = approvals.create({
    type: 'milestone',
    title: 'דירוג שלב 1 - גרין ליף',
    clientName: client4.name,
    status: 'approved',
    createdAt: now,
    updatedAt: now,
  });

  const approval5 = approvals.create({
    type: 'video',
    title: 'סדרת טיפים - סטודיו פיקסל',
    clientName: client1.name,
    status: 'rejected',
    createdAt: now,
    updatedAt: now,
  });

  // Create activity entries
  activities.create({
    type: 'project',
    icon: '🎬',
    title: 'פרויקט חדש: וידיאו פתיחה',
    description: 'וידיאו פתיחה לדוקומנטר של סטודיו פיקסל הושלם',
    entityId: project1.id,
    userId: user1.id,
    createdAt: now,
  });

  activities.create({
    type: 'render',
    icon: '⚙️',
    title: 'התחיל ביצוע הביצוע',
    description: 'התחיל ביצוע וידיאו פרסומי של ברנדיפיי',
    entityId: project2.id,
    userId: user1.id,
    createdAt: now,
  });

  activities.create({
    type: 'client',
    icon: '👥',
    title: 'לקוח חדש: סטודיו פיקסל',
    description: 'סטודיו פיקסל הוסף כלקוח פעיל',
    entityId: client1.id,
    userId: user1.id,
    createdAt: now,
  });

  activities.create({
    type: 'task',
    icon: '✓',
    title: 'משימה הושלמה: ערוך וידיאו',
    description: 'משימה ערוך וידיאו של דנה הושלמה',
    entityId: task2.id,
    userId: user2.id,
    createdAt: now,
  });

  activities.create({
    type: 'payment',
    icon: '💰',
    title: 'תשלום בוצע',
    description: 'תשלום של 8500 שקל בוצע עבור סטודיו פיקסל',
    entityId: payment1.id,
    userId: user1.id,
    createdAt: now,
  });

  activities.create({
    type: 'lead',
    icon: '📞',
    title: 'לידו חדשה: אברהם גולדברג',
    description: 'לידו חדשה מ-אתר האינטרנט לפרויקט סרטון תדירות',
    entityId: lead1.id,
    userId: user3.id,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  });

  activities.create({
    type: 'ai',
    icon: '🤖',
    title: 'ניתוח אוטומטי הושלם',
    description: 'ניתוח AI של הדמיה טכנולוגית הושלם בהצלחה',
    entityId: project3.id,
    userId: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  });

  activities.create({
    type: 'project',
    icon: '🎬',
    title: 'סטטוס פרויקט עודכן',
    description: 'קמפיין סוציאלי של גרין ליף עודכן לאושר',
    entityId: project4.id,
    userId: user1.id,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  });

  activities.create({
    type: 'client',
    icon: '👥',
    title: 'פרטי לקוח עודכנו',
    description: 'פרטי יצירת קשר של ברנדיפיי עודכנו',
    entityId: client2.id,
    userId: user1.id,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  });

  activities.create({
    type: 'task',
    icon: '✓',
    title: 'משימה חדשה: כתוב תסריט',
    description: 'משימה חדשה עבור כתיבת תסריט טריילר המשחק',
    entityId: task5.id,
    userId: user3.id,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  });

  // ===== BUSINESS PROJECTS =====
  const bProject1 = businessProjects.create({
    projectName: 'מיתוג מחדש - קפה שמש',
    clientId: client1.id,
    projectType: 'branding',
    description: 'עיצוב לוגו חדש, צבעים, פונטים וחומרי מיתוג מלאים',
    agreementSigned: true,
    projectStatus: 'in_progress',
    startDate: '2026-03-01',
    endDate: '2026-05-15',
    assignedManagerId: employee1.id,
    createdAt: now,
    updatedAt: now,
  });

  const bProject2 = businessProjects.create({
    projectName: 'אתר תדמית - ברנדיפיי',
    clientId: client2.id,
    projectType: 'website',
    description: 'בניית אתר תדמית רספונסיבי כולל דף נחיתה וטפסים',
    agreementSigned: true,
    projectStatus: 'waiting_for_client',
    startDate: '2026-02-15',
    endDate: '2026-04-30',
    assignedManagerId: employee1.id,
    createdAt: now,
    updatedAt: now,
  });

  const bProject3 = businessProjects.create({
    projectName: 'קמפיין השקה - סטודיו פלקס',
    clientId: client3.id,
    projectType: 'campaign',
    description: 'קמפיין דיגיטלי להשקת מוצר חדש כולל לנדינג ופרסום',
    agreementSigned: false,
    projectStatus: 'not_started',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    assignedManagerId: employee2.id,
    createdAt: now,
    updatedAt: now,
  });

  const bProject4 = businessProjects.create({
    projectName: 'עיצוב לוגו - דיגימרקט',
    clientId: client4.id,
    projectType: 'branding',
    description: 'עיצוב לוגו ראשי + וריאציות',
    agreementSigned: true,
    projectStatus: 'completed',
    startDate: '2026-01-10',
    endDate: '2026-02-28',
    assignedManagerId: employee1.id,
    createdAt: now,
    updatedAt: now,
  });

  // ===== PROJECT MILESTONES =====
  projectMilestones.create({
    projectId: bProject1.id,
    title: 'מחקר ואפיון',
    description: 'מחקר מתחרים, אפיון שפה ויזואלית',
    dueDate: '2026-03-15',
    assignedEmployeeId: employee2.id,
    status: 'approved',
    files: [],
    notes: 'הושלם בזמן',
    createdAt: now,
    updatedAt: now,
  });

  projectMilestones.create({
    projectId: bProject1.id,
    title: 'עיצוב לוגו',
    description: '3 כיווני עיצוב ללוגו',
    dueDate: '2026-04-01',
    assignedEmployeeId: employee2.id,
    status: 'in_progress',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  projectMilestones.create({
    projectId: bProject1.id,
    title: 'חומרי מיתוג',
    description: 'כרטיסי ביקור, ניירת, חתימת מייל',
    dueDate: '2026-04-20',
    assignedEmployeeId: employee3.id,
    status: 'pending',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  projectMilestones.create({
    projectId: bProject2.id,
    title: 'עיצוב אתר',
    description: 'עיצוב דפי האתר ב-Figma',
    dueDate: '2026-03-15',
    assignedEmployeeId: employee2.id,
    status: 'submitted',
    files: [],
    notes: 'ממתין לאישור לקוח',
    createdAt: now,
    updatedAt: now,
  });

  projectMilestones.create({
    projectId: bProject2.id,
    title: 'פיתוח אתר',
    description: 'בניית האתר בפועל',
    dueDate: '2026-04-15',
    assignedEmployeeId: employee1.id,
    status: 'pending',
    files: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  // ===== PROJECT PAYMENTS =====
  projectPayments.create({
    projectId: bProject1.id,
    clientId: client1.id,
    amount: 3000,
    dueDate: '2026-03-01',
    status: 'paid',
    description: 'מקדמה - 50%',
    paidAt: '2026-03-02',
    createdAt: now,
    updatedAt: now,
  });

  projectPayments.create({
    projectId: bProject1.id,
    clientId: client1.id,
    amount: 3000,
    dueDate: '2026-05-15',
    status: 'pending',
    description: 'יתרה - 50%',
    paidAt: null,
    createdAt: now,
    updatedAt: now,
  });

  projectPayments.create({
    projectId: bProject2.id,
    clientId: client2.id,
    amount: 5000,
    dueDate: '2026-02-15',
    status: 'paid',
    description: 'מקדמה - 40%',
    paidAt: '2026-02-16',
    createdAt: now,
    updatedAt: now,
  });

  projectPayments.create({
    projectId: bProject2.id,
    clientId: client2.id,
    amount: 4000,
    dueDate: '2026-04-01',
    status: 'collection_needed',
    description: 'תשלום שני - 30%',
    paidAt: null,
    createdAt: now,
    updatedAt: now,
  });

  projectPayments.create({
    projectId: bProject2.id,
    clientId: client2.id,
    amount: 3500,
    dueDate: '2026-04-30',
    status: 'pending',
    description: 'יתרה - 30%',
    paidAt: null,
    createdAt: now,
    updatedAt: now,
  });

  projectPayments.create({
    projectId: bProject3.id,
    clientId: client3.id,
    amount: 4500,
    dueDate: '2026-05-01',
    status: 'pending',
    description: 'תשלום מלא',
    paidAt: null,
    createdAt: now,
    updatedAt: now,
  });

  // ===== HOSTING RECORDS =====
  hostingRecords.create({
    clientId: client1.id,
    domainName: 'cafe-shemesh.co.il',
    hostingProvider: 'Bluehost',
    yearlyPaymentAmount: 450,
    nextPaymentDate: '2026-06-15',
    lastPaidDate: '2025-06-15',
    status: 'active',
    notes: 'כולל SSL',
    createdAt: now,
    updatedAt: now,
  });

  hostingRecords.create({
    clientId: client2.id,
    domainName: 'brandify.co.il',
    hostingProvider: 'SiteGround',
    yearlyPaymentAmount: 600,
    nextPaymentDate: '2026-04-20',
    lastPaidDate: '2025-04-20',
    status: 'expiring_soon',
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  hostingRecords.create({
    clientId: client3.id,
    domainName: 'studioflex.com',
    hostingProvider: 'Cloudways',
    yearlyPaymentAmount: 720,
    nextPaymentDate: '2026-03-01',
    lastPaidDate: '2025-03-01',
    status: 'overdue',
    notes: 'צריך לעדכן כרטיס אשראי',
    createdAt: now,
    updatedAt: now,
  });

  hostingRecords.create({
    clientId: client4.id,
    domainName: 'digimarket.co.il',
    hostingProvider: 'Bluehost',
    yearlyPaymentAmount: 350,
    nextPaymentDate: '2026-09-01',
    lastPaidDate: '2025-09-01',
    status: 'active',
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  // ===== ACCOUNTANT DOCUMENTS =====
  accountantDocuments.create({
    period: 'jan-feb',
    periodLabel: 'ינואר-פברואר 2026',
    year: 2026,
    fileName: 'invoices-jan-feb-2026.pdf',
    fileUrl: '/uploads/invoices-jan-feb-2026.pdf',
    fileType: 'invoice',
    notes: 'חשבוניות חודשיים ראשונים',
    sentToAccountant: true,
    sentAt: '2026-03-05',
    createdAt: now,
    updatedAt: now,
  });

  accountantDocuments.create({
    period: 'jan-feb',
    periodLabel: 'ינואר-פברואר 2026',
    year: 2026,
    fileName: 'receipts-jan-feb-2026.pdf',
    fileUrl: '/uploads/receipts-jan-feb-2026.pdf',
    fileType: 'receipt',
    notes: '',
    sentToAccountant: true,
    sentAt: '2026-03-05',
    createdAt: now,
    updatedAt: now,
  });

  accountantDocuments.create({
    period: 'mar-apr',
    periodLabel: 'מרץ-אפריל 2026',
    year: 2026,
    fileName: 'invoices-mar-apr-2026.pdf',
    fileUrl: '/uploads/invoices-mar-apr-2026.pdf',
    fileType: 'invoice',
    notes: 'טרם נשלח',
    sentToAccountant: false,
    sentAt: null,
    createdAt: now,
    updatedAt: now,
  });

  // ===== PODCAST SESSIONS =====
  podcastSessions.create({
    clientId: client1.id,
    clientName: client1.name,
    packageType: 'recording_3_videos',
    price: 849,
    sessionDate: '2026-04-14',
    startTime: '10:00',
    endTime: '11:30',
    sessionStatus: 'booked',
    contentStatus: 'pending_upload',
    agreementPdfUrl: '',
    agreementSent: true,
    videosCount: 3,
    draftUrls: [],
    finalUrls: [],
    paymentStatus: 'pending',
    paidAt: null,
    notes: 'הקלטה ראשונה ללקוח',
    createdAt: now,
    updatedAt: now,
  });

  podcastSessions.create({
    clientId: client3.id,
    clientName: client3.name,
    packageType: 'recording_5_videos',
    price: 999,
    sessionDate: '2026-04-10',
    startTime: '14:00',
    endTime: '15:30',
    sessionStatus: 'completed',
    contentStatus: 'client_review',
    agreementPdfUrl: '',
    agreementSent: true,
    videosCount: 5,
    draftUrls: ['/uploads/draft1.mp4', '/uploads/draft2.mp4'],
    finalUrls: [],
    paymentStatus: 'paid',
    paidAt: '2026-04-10',
    notes: 'הקלטה מעולה',
    createdAt: now,
    updatedAt: now,
  });

  podcastSessions.create({
    clientId: client5.id,
    clientName: client5.name,
    packageType: 'recording_10_videos',
    price: 1749,
    sessionDate: '2026-04-18',
    startTime: '09:00',
    endTime: '10:30',
    sessionStatus: 'booked',
    contentStatus: 'pending_upload',
    agreementPdfUrl: '',
    agreementSent: false,
    videosCount: 10,
    draftUrls: [],
    finalUrls: [],
    paymentStatus: 'pending',
    paidAt: null,
    notes: 'חבילה מורחבת',
    createdAt: now,
    updatedAt: now,
  });

  podcastSessions.create({
    clientId: client2.id,
    clientName: client2.name,
    packageType: 'recording_only',
    price: 497,
    sessionDate: '2026-04-05',
    startTime: '16:00',
    endTime: '17:30',
    sessionStatus: 'completed',
    contentStatus: 'completed',
    agreementPdfUrl: '',
    agreementSent: true,
    videosCount: 0,
    draftUrls: [],
    finalUrls: [],
    paymentStatus: 'paid',
    paidAt: '2026-04-05',
    notes: '',
    createdAt: now,
    updatedAt: now,
  });

  // ===== AI SETTINGS =====
  aiSettings.create({
    provider: 'openai',
    apiKey: '',
    defaultModel: 'gpt-4.1',
    connectionStatus: 'missing_key',
    lastTestedAt: null,
    lastTestError: '',
    assemblyaiApiKey: '',
    assemblyaiConnectionStatus: 'missing_key',
    assemblyaiLastTestedAt: null,
    assemblyaiLastTestError: '',
    primaryTranscriptionProvider: 'assemblyai',
    fallbackTranscriptionProvider: 'whisper',
    createdAt: now,
    updatedAt: now,
  });

  // ===== GMAIL SETTINGS =====
  gmailSettings.create({
    connectionStatus: 'not_connected',
    connectedEmail: '',
    accessToken: '',
    refreshToken: '',
    tokenExpiresAt: null,
    senderDisplayName: 'Studio Pixel',
    replyToEmail: '',
    defaultSignature: '<p style="color:#888;font-size:13px;">בברכה,<br/>סטודיו פיקסל<br/>Studio Pixel</p>',
    lastSyncAt: null,
    lastError: '',
    isSystemEmailOrigin: true,
    createdAt: now,
    updatedAt: now,
  });

  // ===== CLIENT KNOWLEDGE =====
  clientKnowledge.create({
    clientId: client1.id,
    websiteSummary: 'סטודיו פיקסל מתמחה ביצירת תוכן ווידיאו דיגיטלי. מציעים שירותי עריכה, אנימציה והפקה.',
    facebookInsights: 'קהל עוקבים מגוון, פוסטים בעיקר על פרויקטים חדשים והדרכות',
    instagramInsights: 'תוכן ויזואלי מרהיב, דגש על before/after של פרויקטים',
    businessContext: 'חברה מובילה בתעשיית יצירת תוכן ווידיאו, לקוחות מתחום הביזנס והמותגים',
    toneAndStyle: 'מקצועי אך נגיש, צבעוני, מעורר השראה',
    audienceProfile: 'בעלי עסקים קטנים ובינוניים, מנהלי שיווק, יוצרי תוכן',
    previousContentThemes: ['פרויקטים חדשים', 'טיפים לווידיאו', 'מאחורי הקלעים', 'לקוחות מרוצים'],
    approvedCaptionStyles: ['קצר וקולע', 'שאלה פתוחה', 'סיפור אישי קצר'],
    topPerformingFormats: ['reel', 'carousel', 'video'],
    pastCampaigns: ['השקת מותג 2025', 'Black Friday 2025', 'חג הפסח'],
    seasonalPatterns: 'פעילות מוגברת לקראת חגים, ירידה באוגוסט',
    lastUpdatedSources: ['website', 'facebook', 'instagram'],
    lastEnrichedAt: now,
    createdAt: now,
    updatedAt: now,
  });
}

export function resetSeed(): void {
  // This is a no-op in the new implementation since we use count() to check if empty
  // The seed will only run if collections are empty
  // This function is kept for API compatibility with existing code
}
