#!/bin/bash
#
# PixelManageAI — Remotion Lambda Setup (one-time)
#
# Usage:
#   1. Create an AWS account at https://aws.amazon.com if you don't have one
#   2. Create an IAM user with these permissions:
#      - AmazonS3FullAccess
#      - AWSLambda_FullAccess
#      - IAMFullAccess (only needed for first deploy)
#   3. Copy your Access Key ID + Secret from IAM console
#   4. Run: ./scripts/setup-remotion-lambda.sh
#
# The script will:
#   - Deploy the Remotion Lambda function
#   - Deploy your video site bundle to S3
#   - Create a .env.lambda file with all needed variables
#   - Optionally add them to your Vercel project
#

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔════════════════════════════════════════════╗"
echo "║   PixelManageAI — Remotion Lambda Setup    ║"
echo "╚════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Step 1: Check for AWS credentials ──────────────────────────────────

if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo -e "${YELLOW}AWS credentials not found in environment.${NC}"
  echo ""
  read -p "Enter your AWS Access Key ID: " AWS_ACCESS_KEY_ID
  read -sp "Enter your AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
  echo ""
  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY
fi

# Region
REGION="${AWS_REGION:-us-east-1}"
read -p "AWS Region [${REGION}]: " INPUT_REGION
REGION="${INPUT_REGION:-$REGION}"
export AWS_REGION="$REGION"

echo ""
echo -e "${CYAN}Using region: ${REGION}${NC}"
echo -e "${CYAN}AWS Key ID:   ${AWS_ACCESS_KEY_ID:0:8}...${NC}"
echo ""

# ── Step 2: Deploy IAM role + Lambda function ──────────────────────────

echo -e "${CYAN}[1/4] Setting up IAM roles...${NC}"
npx remotion lambda policies role --region="$REGION" 2>/dev/null || {
  echo -e "${YELLOW}IAM role setup skipped (may already exist).${NC}"
}

echo ""
echo -e "${CYAN}[2/4] Deploying Lambda function...${NC}"
DEPLOY_OUTPUT=$(npx remotion lambda functions deploy \
  --region="$REGION" \
  --memory=3009 \
  --timeout=240 \
  --disk=2048 \
  2>&1)

echo "$DEPLOY_OUTPUT"

# Extract function name from output
FUNCTION_NAME=$(echo "$DEPLOY_OUTPUT" | grep -oP '(?<=Function name: ).*' || \
                echo "$DEPLOY_OUTPUT" | grep -oP 'remotion-render-[a-z0-9-]+' | head -1)

if [ -z "$FUNCTION_NAME" ]; then
  echo -e "${YELLOW}Could not auto-detect function name. Listing functions...${NC}"
  npx remotion lambda functions ls --region="$REGION"
  read -p "Enter the function name from above: " FUNCTION_NAME
fi

echo -e "${GREEN}Lambda function: ${FUNCTION_NAME}${NC}"

# ── Step 3: Deploy site bundle to S3 ──────────────────────────────────

echo ""
echo -e "${CYAN}[3/4] Deploying Remotion site bundle to S3...${NC}"
SITE_OUTPUT=$(npx remotion lambda sites create \
  src/remotion/index.ts \
  --site-name=pixelmanage \
  --region="$REGION" \
  2>&1)

echo "$SITE_OUTPUT"

# Extract serve URL
SERVE_URL=$(echo "$SITE_OUTPUT" | grep -oP '(?<=Serve URL: ).*' || \
            echo "$SITE_OUTPUT" | grep -oP 'https://[a-z0-9-]+\.s3\.[a-z0-9-]+\.amazonaws\.com/sites/[^\s]+' | head -1)

if [ -z "$SERVE_URL" ]; then
  echo -e "${YELLOW}Could not auto-detect serve URL. Listing sites...${NC}"
  npx remotion lambda sites ls --region="$REGION"
  read -p "Enter the Serve URL from above: " SERVE_URL
fi

echo -e "${GREEN}Serve URL: ${SERVE_URL}${NC}"

# ── Step 4: Write .env.lambda ──────────────────────────────────────────

echo ""
echo -e "${CYAN}[4/4] Writing environment variables...${NC}"

ENV_FILE=".env.lambda"
cat > "$ENV_FILE" << EOF
# Remotion Lambda — generated by setup-remotion-lambda.sh
# Add these to your Vercel project: vercel env add <KEY>

REMOTION_AWS_REGION=${REGION}
REMOTION_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
REMOTION_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
REMOTION_LAMBDA_FUNCTION_NAME=${FUNCTION_NAME}
REMOTION_SERVE_URL=${SERVE_URL}
EOF

echo -e "${GREEN}Saved to ${ENV_FILE}${NC}"

# Also append to .env.local if it exists
if [ -f ".env.local" ]; then
  echo "" >> .env.local
  echo "# Remotion Lambda (auto-added)" >> .env.local
  cat "$ENV_FILE" >> .env.local
  echo -e "${GREEN}Also appended to .env.local${NC}"
fi

# ── Optional: Push to Vercel ───────────────────────────────────────────

echo ""
read -p "Push these env vars to Vercel now? (y/n): " PUSH_VERCEL

if [ "$PUSH_VERCEL" = "y" ] || [ "$PUSH_VERCEL" = "Y" ]; then
  echo "Adding to Vercel..."
  echo "$REGION" | npx vercel env add REMOTION_AWS_REGION production 2>/dev/null || true
  echo "$AWS_ACCESS_KEY_ID" | npx vercel env add REMOTION_AWS_ACCESS_KEY_ID production 2>/dev/null || true
  echo "$AWS_SECRET_ACCESS_KEY" | npx vercel env add REMOTION_AWS_SECRET_ACCESS_KEY production 2>/dev/null || true
  echo "$FUNCTION_NAME" | npx vercel env add REMOTION_LAMBDA_FUNCTION_NAME production 2>/dev/null || true
  echo "$SERVE_URL" | npx vercel env add REMOTION_SERVE_URL production 2>/dev/null || true
  echo -e "${GREEN}Vercel env vars set!${NC}"
  echo -e "${YELLOW}Run 'vercel --prod' to redeploy with new vars.${NC}"
fi

# ── Done ───────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          Setup Complete!                    ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo "Summary:"
echo "  Region:        ${REGION}"
echo "  Function:      ${FUNCTION_NAME}"
echo "  Serve URL:     ${SERVE_URL}"
echo "  Env file:      ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Push code:  git add -A && git commit -m 'feat: Remotion Lambda' && git push"
echo "  2. Deploy:     vercel --prod"
echo "  3. Test:       Try rendering a video in the app!"
echo ""
